src/WebUI/Models/ErrorViewModel.cs
namespace GolfCaddie.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebUI/Controllers/HomeController.cs
using GolfCaddie.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebUI/Controllers/ScoreCardController.cs
using GolfCaddie.Application.Common.Models;
using GolfCaddie.Application.ScoreCardCQRS.Commands.CreateScoreCard;
using GolfCaddie.Application.ScoreCardCQRS.Commands.DeleteScoreCard;
using GolfCaddie.Application.ScoreCardCQRS.Commands.UpdateScoreCard;
using GolfCaddie.Application.ScoreCardCQRS.Queries.GetScoreCard;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers;

public class ScoreCardController : Controller
{
    private readonly IMediator _mediator;

    public ScoreCardController(IMediator mediator)
    {
        _mediator = mediator;
    }

    // Get All ScoreCards
    [HttpGet]
    public async Task<IActionResult> ViewScoreCard()
    {
        var query = new GetAllScoreCardsQuery();
        var scoreCard = await _mediator.Send(query);

        if (scoreCard == null)
        {
            return NotFound();
        }

        return View(scoreCard);
    }

    // Navigate to Add ScoreCard
    public IActionResult AddScoreCard()
    {
        return View("AddScoreCard");
    }

    // Add ScoreCard
    [HttpPost]
    public async Task<IActionResult> AddScoreCard(CreateScoreCardCommand command, ScoreCardDto scoreCardDto)
    {
        await _mediator.Send(command);
        return View("~/Views/ScoreCard/AddScoreCard.cshtml");
    }

    // Delete a ScoreCard
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteScoreCard(int id)
    {
        var command = new DeleteScoreCardCommand(id);
        var result = await _mediator.Send(command);

        if (result)
        {
            return View("Home");
        }
        else
        {
            return NotFound(); // 404 Not Found
        }
    }

    public async Task<IActionResult> EditScoreCard(int id)
    {
        var query = new GetScoreCardByIdQuery { ScoreCardId = id };
        var scoreCard = await _mediator.Send(query);

        if (scoreCard == null)
        {
            return NotFound();
        }

        return View(scoreCard);
    }

    // Edit ScoreCard
    [HttpPost]
    public async Task<IActionResult> EditScoreCard(int id, UpdateScoreCardCommand command, ScoreCardDto scoreCardDto)
    {
        command.Id = id;
        await _mediator.Send(command);

        return RedirectToAction(nameof(ViewScoreCard));
    }
}

src/WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Golf Caddie</h1>
</div>

src/WebUI/Views/ScoreCard/AddScoreCard.cshtml
@{
    ViewData["Title"] = "AddScoreCard";
}

<h1>Add Score Card</h1>

<html>
<head>
    <title>Enter Score</title>
    <link href="scorecardStyle.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <form asp-asp-controller="ScoreCardController" asp-action="AddScoreCard" method="post">
        <h1 class="header text-center"> <input name="scoreCardDto.CourseName"><strong></strong></input></h1>
        <div class="text-center m-3">
            <input style="background-color:dimgrey; color: floralwhite" type="date" id="start" name="scoreCardDto.Date" />
        </div>        
        <div class="table-responsive">
            <table class="table table-condensed table-bordered">

                @* Hole Numbers *@
                <tr class="success text-center">
                    <th class="text-left">Hole</th>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                    <th class="text-uppercase"><strong>Out</strong></th>
                    <td>10</td>
                    <td>11</td>
                    <td>12</td>
                    <td>13</td>
                    <td>14</td>
                    <td>15</td>
                    <td>16</td>
                    <td>17</td>
                    <td>18</td>
                    <th class="text-uppercase">In</th>
                    <th class="text-uppercase">Total</th>
                </tr>

                @* Par *@
                <tr id="par" class="text-center" style="background-color: black; color: white;">
                    <td class="text-left"><strong>Par</strong></td>
                    @for(int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        <td><input name="scoreCardDto.Holes[@i].Par" type="number" min="3" max="99" style="background-color: black;" /></td>
                    }              
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Strokes *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Strokes</strong></td>
                    @for(int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        <td><input name="scoreCardDto.Holes[@i].Score" type="number" min="0" max="99" /> </td>
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Putts *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Putts</strong></td>
                    @for(int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        <td><input name="scoreCardDto.Holes[@i].Putts" type="number" min="0" max="99" /> </td>
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Penalties *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Penalties</strong></td>
                    @for(int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        <td><input name="scoreCardDto.Holes[@i].Penalties" type="number" min="0" max="99" /> </td>
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>
            </table>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Submit</button>
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.slim.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="./scorecard.js"></script>
</body>
</html>

src/WebUI/Views/ScoreCard/EditScoreCard.cshtml
@{
    ViewData["Title"] = "EditScoreCard";
}

<h1>Edit Score Card</h1>

<html>
<head>
    <title>Enter Score</title>
    <link href="scorecardStyle.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <form asp-action="EditScoreCard" asp-route-id="@Model.ScoreCardId" method="post">
        <h1 class="header text-center"> <input name="scoreCardDto.CourseName" value="@Model.CourseName"><strong></strong></input></h1>
        <div class="text-center m-3">
            <input style="background-color:dimgrey; color: floralwhite" type="date" id="start" name="scoreCardDto.Date" value="@Model.Date.ToString("yyyy-MM-dd")" />
        </div>
        <div class="table-responsive">
            <table class="table table-condensed table-bordered">

                @* Hole Numbers *@
                <tr class="success text-center">
                    <th class="text-left">Hole</th>
                    @for (int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <th class="text-uppercase"><strong>Out</strong></th>
                        }                      
                        
                        var holeNumber = i + 1;
                        <td>@holeNumber</td>
                    }
                    <th class="text-uppercase">In</th>
                    <th class="text-uppercase">Total</th>
                </tr>

                @* Par *@
                <tr id="par" class="text-center" style="background-color: black; color: white;">
                    <td class="text-left"><strong>Par</strong></td>
                    @{
                        var holeIndex = 0;
                    }
                    @for (int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        if (holeIndex < Model.Holes.Count)
                        {
                            if ((i + 1) == Model.Holes[holeIndex].HoleNumber)
                            {
                                <td><input name="scoreCardDto.Holes[@i].Par" type="number" min="3" max="99" style="background-color: black;" value="@Model.Holes[holeIndex].Par" /></td>
                                holeIndex++;
                            }
                            else
                            {
                                <td><input name="scoreCardDto.Holes[@i].Par" type="number" min="3" max="99" style="background-color: black;" /></td>
                            }
                        }
                        else
                        {
                            <td><input name="scoreCardDto.Holes[@i].Par" type="number" min="3" max="99" style="background-color: black;" /></td>
                        }
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Strokes *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Strokes</strong></td>
                    @{
                        holeIndex = 0;
                    }
                    @for (int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        if (holeIndex < Model.Holes.Count)
                        {
                            if ((i + 1) == Model.Holes[holeIndex].HoleNumber)
                            {
                                <td><input name="scoreCardDto.Holes[@i].Score" type="number" min="0" max="99" value="@Model.Holes[holeIndex].Score" /> </td>
                                holeIndex++;
                            }
                            else
                            {
                                <td><input name="scoreCardDto.Holes[@i].Score" type="number" min="0" max="99" /> </td>
                            }
                        }
                        else
                        {
                            <td><input name="scoreCardDto.Holes[@i].Score" type="number" min="0" max="99" /> </td>
                        }
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Putts *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Putts</strong></td>
                    @{
                        holeIndex = 0;
                    }
                    @for (int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        if (holeIndex < Model.Holes.Count)
                        {
                            if ((i + 1) == Model.Holes[holeIndex].HoleNumber)
                            {
                                <td><input name="scoreCardDto.Holes[@i].Putts" type="number" min="0" max="99" value="@Model.Holes[holeIndex].Putts" /> </td>
                                holeIndex++;
                            }
                            else
                            {
                                <td><input name="scoreCardDto.Holes[@i].Putts" type="number" min="0" max="99" /> </td>
                            }
                        }
                        else
                        {
                            <td><input name="scoreCardDto.Holes[@i].Putts" type="number" min="0" max="99" /> </td>
                        }
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>

                @* Penalties *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Penalties</strong></td>
                    @{
                        holeIndex = 0;
                    }
                    @for (int i = 0; i < 18; i++)
                    {
                        if (i == 9)
                        {
                            <td class="disabled"></td>
                        }
                        if (holeIndex < Model.Holes.Count)
                        {
                            if ((i + 1) == Model.Holes[holeIndex].HoleNumber)
                            {
                                <td><input name="scoreCardDto.Holes[@i].Penalties" type="number" min="0" max="99" value="@Model.Holes[holeIndex].Penalties" /> </td>
                                holeIndex++;
                            }
                            else
                            {
                                <td><input name="scoreCardDto.Holes[@i].Penalties" type="number" min="0" max="99" /> </td>
                            }
                        }
                        else
                        {
                            <td><input name="scoreCardDto.Holes[@i].Penalties" type="number" min="0" max="99" /> </td>
                        }
                    }
                    <td class="disabled"></td>
                    <td id="total" class="disabled"></td>
                </tr>
            </table>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Save</button>
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.slim.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="./scorecard.js"></script>
</body>
</html>

src/WebUI/Views/ScoreCard/ViewScoreCard.cshtml
@model List<GolfCaddie.Application.Common.Models.ScoreCardDto>
@{
    ViewData["Title"] = "ViewScoreCard";
}

<div class="text-center">
    <h1 class="display-4">Scorecards</h1>
</div>

<html>
<head>
    <title>Previous Scores</title>
    <link href="scorecardStyle.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    @foreach (var scorecard in Model)
    {
        var holeList = scorecard.Holes.ToList();

        <h1 class="header text-center"> <strong>@scorecard.CourseName - @scorecard.Date.ToString("MMMM dd, yyyy")</strong></h1>
        <div class="table-responsive">
            <table class="table table-condensed table-bordered">

                @* Hole Numbers *@
                <tr class="success text-center">
                    <th class="text-left">Hole</th>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                    <th class="text-uppercase text-center"><strong>Out</strong></th>
                    <td>10</td>
                    <td>11</td>
                    <td>12</td>
                    <td>13</td>
                    <td>14</td>
                    <td>15</td>
                    <td>16</td>
                    <td>17</td>
                    <td>18</td>
                    <th class="text-uppercase text-center">In</th>
                    <th class="text-uppercase text-center">Total</th>
                </tr>

                @* Par *@
                <tr id="par" class="text-center" style="background-color: black; color: white;">
                    <td class="text-left"><strong>Par</strong></td>
                    @{
                        var currentHolePar = 0;
                        var frontPar = 0;
                        var backPar = 0;
                    }
                    @for (var holeCounter = 1; holeCounter < 19; holeCounter++)
                    {
                        if (holeList[currentHolePar].HoleNumber == holeCounter)
                        {
                            <td>@holeList[currentHolePar].Par</td>

                            if (holeCounter <= 9)
                            {
                                frontPar += holeList[currentHolePar].Par;
                            }
                            if (holeCounter > 9 && holeCounter <= 18)
                            {
                                backPar += holeList[currentHolePar].Par;
                            }
                            if (holeList.Count() > currentHolePar + 1)
                            {
                                currentHolePar++;
                            }                            
                        }

                        else
                        {
                            <td></td>
                        }

                        if (holeCounter == 9)
                        {
                            <td>@frontPar</td>
                        }
                        if (holeCounter == 18)
                        {
                            if (backPar != 0)
                            {
                                <td>@backPar</td>
                            }
                            else
                            {
                                <td></td>
                            }
                        }
                    }
                    @{
                        var totalPar = frontPar + backPar;
                    }
                    <td id="total">@totalPar</td>
                </tr>

                @* Strokes *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Strokes</strong></td>
                    @{
                        var currentHoleStrokes = 0;
                        var frontStrokes = 0;
                        var backStrokes = 0;
                    }
                    @for (var holeCounter = 1; holeCounter < 19; holeCounter++)
                    {
                        if (holeList[currentHoleStrokes].HoleNumber == holeCounter)
                        {
                            <td>@holeList[currentHoleStrokes].Score</td>

                            if (holeCounter <= 9)
                            {
                                frontStrokes += holeList[currentHoleStrokes].Score;
                            }
                            if (holeCounter > 9 && holeCounter <= 18)
                            {
                                backStrokes += holeList[currentHoleStrokes].Score;
                            }
                            if (holeList.Count() > currentHoleStrokes + 1)
                            {
                                currentHoleStrokes++;
                            }
                        }

                        else
                        {
                            <td></td>
                        }

                        if (holeCounter == 9)
                        {
                            <td>@frontStrokes</td>
                        }
                        if (holeCounter == 18)
                        {
                            if (backStrokes != 0)
                            {
                                <td>@backStrokes</td>
                            }
                            else
                            {
                                <td></td>
                            }
                        }
                    }
                    @{
                        var totalStrokes = frontStrokes + backStrokes;
                    }
                    <td id="total">@totalStrokes</td>
                </tr>

                @* Putts *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Putts</strong></td>
                    @{
                        var currentHolePutts = 0;
                        var frontPutts = 0;
                        var backPutts = 0;
                    }
                    @for (var holeCounter = 1; holeCounter < 19; holeCounter++)
                    {
                        if (holeList[currentHolePutts].HoleNumber == holeCounter)
                        {
                            <td>@holeList[currentHolePutts].Putts</td>

                            if (holeCounter <= 9)
                            {
                                frontPutts += holeList[currentHolePutts].Putts;
                            }
                            if (holeCounter > 9 && holeCounter <= 18)
                            {
                                backPutts += holeList[currentHolePutts].Putts;
                            }
                            if (holeList.Count() > currentHolePutts + 1)
                            {
                                currentHolePutts++;
                            }
                        }

                        else
                        {
                            <td></td>
                        }

                        if (holeCounter == 9)
                        {
                            <td>@frontPutts</td>
                        }
                        if (holeCounter == 18)
                        {
                            if (backPutts != 0)
                            {
                                <td>@backPutts</td>
                            }
                            else
                            {
                                <td></td>
                            }
                        }
                    }
                    @{
                        var totalPutts = frontPutts + backPutts;
                    }
                    <td id="total">@totalPutts</td>
                </tr>

                @* Penalties *@
                <tr class="score text-center">
                    <td class="text-left"><strong>Penalties</strong></td>
                    @{
                        var currentHolePenalties = 0;
                        var frontPenalties = 0;
                        var backPenalties = 0;
                    }
                    @for (var holeCounter = 1; holeCounter < 19; holeCounter++)
                    {
                        if (holeList[currentHolePenalties].HoleNumber == holeCounter)
                        {
                            <td>@holeList[currentHolePenalties].Penalties</td>

                            if (holeCounter <= 9)
                            {
                                frontPenalties += holeList[currentHolePenalties].Penalties;
                            }
                            if (holeCounter > 9 && holeCounter <= 18)
                            {
                                backPenalties += holeList[currentHolePenalties].Penalties;
                            }
                            if (holeList.Count() > currentHolePenalties + 1)
                            {
                                currentHolePenalties++;
                            }
                        }

                        else
                        {
                            <td></td>
                        }

                        if (holeCounter == 9)
                        {
                            <td>@frontPenalties</td>
                        }
                        if (holeCounter == 18)
                        {
                            if (backPar != 0)
                            {
                                <td>@backPenalties</td>
                            }
                            else
                            {
                                <td></td>
                            }
                        }
                    }
                    @{
                        var totalPenalties = frontPenalties + backPenalties;
                    }
                    <td id="total">@totalPenalties</td>
                </tr>
            </table>
        </div>
        <div>
            <a href="/ScoreCard/EditScoreCard?id=@scorecard.ScoreCardId"><button class="btn btn-light btn-sm">Edit</button></a>
        </div>
        <div>
            <a asp-controller="ScoreCard" asp-action=""><button class="btn btn-danger btn-sm">Delete</button></a>
        </div>
    }
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.slim.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="./scorecard.js"></script>
</body>
</html>

src/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GolfCaddie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GolfCaddie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ScoreCard" asp-action="ViewScoreCard">Scores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ScoreCard" asp-action="AddScoreCard">Add Score</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; GolfCaddie 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>